### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by Debik5** [igoogolx/lux#9]
Hi
when trying to connect in version 0.2.8, the connection is not established, unlike earlier versions of the application. In the application logs I see a lot of errors like : failed to get tcp conn, err: example:21356 connect error: lookup example: i/o timeout, rule: 1, remote ip: 8.8.8.8

![Снимок экрана 2023-08-13 134154](https://github.com/igoogolx/lux/assets/79472703/22a1fbd3-fcbb-458a-82f0-1e535e8acb4b)

**Comment by igoogolx** [comment]
Is your proxy address an IP or a domain name?

**Comment by igoogolx** [comment]
When lux is **not** connected, is your proxy's Connectivity Test ok?

![image](https://github.com/igoogolx/lux/assets/27353191/2d1c7ea0-656f-4ad5-9cc3-8fc46551ccb7)

**Comment by igoogolx** [comment]
When lux is not connected, is your proxy's Connectivity Test ok?

![image](https://github.com/igoogolx/lux/assets/27353191/a6ea9d1f-5843-41f3-805e-a6441ff1d281)

**Comment by igoogolx** [comment]
When lux **is** connected, what is the runtime detail?

![image](https://github.com/igoogolx/lux/assets/27353191/10af4027-30da-4df5-abf7-f6d3513036b9)

**Comment by Debik5** [comment]
> When lux is **not** connected, is your proxy's Connectivity Test ok?
> 
> ![image](https://user-images.githubusercontent.com/27353191/260313540-a6ea9d1f-5843-41f3-805e-a6441ff1d281.png)

Yes

**Comment by Debik5** [comment]
> When lux **is** connected, what is the runtime detail?
> 
> ![image](https://user-images.githubusercontent.com/27353191/260313670-10af4027-30da-4df5-abf7-f6d3513036b9.png)

![Снимок экрана 2023-08-16 192549](https://github.com/igoogolx/lux/assets/79472703/95a6caed-39d9-431b-905b-bb299d486785)

**Comment by Debik5** [comment]
> IP

domain

**Comment by igoogolx** [comment]
Since your proxy address is a domain name, it will be resolved by the local DNS. However, 119.29.29.29 is a DNS server in mainland China, and I believe it cannot be accessed properly in your country. You can test it by executing the command "ping 119.29.29.29" in the command line. There are two ways to solve this problem:

1. Use an IP address instead of a domain name as the server. Use the command "ping $your_domain" to obtain the IP address.

2. Use your local DNS server. Download the v0.3.0+1 app and go to the settings page. Edit the local DNS configuration in the settings.

![image](https://github.com/igoogolx/lux/assets/27353191/b830337e-68bb-4f38-b783-ab3f4890cf7d)
